name: Deploy to Amazon S3
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello Douglas this is a messsage for you using ${{ secrets.AWS_ACCESS_KEY_ID }} and ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          subject: Github Actions job result
          to: dbbrauner@gmail.com,brauned@amazon.com
          from: Luke Skywalker # <user@example.com>
          body: Build job of ${{github.repository}} completed successfully!

      - run: echo "finish email"

      - name: Checkout
        uses: actions/checkout@master
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.0
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      
      - name: Upload files
        uses: ItsKarma/aws-cli@master
        with:
          args: s3 sync _site/ s3://brauner.xyz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
