name: Deploy to Amazon S3
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Upload files
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync _site/ s3://brauner.xyz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
